version: '2'
services:
  web-app:
    build: ./app/
    image: dockerguatemala/giphy-nodejs
    restart: unless-stopped
    volumes:
      - "./app/:/app"
    ports: 
      - "127.0.0.1:3000:3000"
    container_name: docker101
    networks:
      - frontend

  nginx:
    container_name: docker101-nginx
    build: ./nginx/
    image: dockerguatemala/giphy-nginx
    restart: unless-stopped
    volumes: 
      - "./nginx/conf.d:/etc/nginx/conf.d/"
    ports: 
      - "8080:80"
    networks:
      - frontend
    # links: 
    #   - "web-app:web-app"

networks:
  frontend: